name: Minesweeper
version: '${version}'
main: com.rtcal.minesweeper.Main
api-version: 1.18
authors: [ rtcal ]
description: Minesweeper implemented in minecraft
depend:
  - ArenaHandler
  - PlayerHandler
commands:
  minesweeper:
    description: Base minesweeper commands
permissions:
  minesweeper.all:
    description: Access to the base minesweeper command
    default: op
    children:
      minesweeper.create: false